Add a setup.py to generate the script
nlohmann/swagger_to_uml pull request #17
Opened 2020-11-06 13:50 UTC by rodfersou

this way we can install easily with pipx:

```
pipx install git+https://github.com/rodfersou/swagger_to_uml.git
```

2020-11-07 13:08 UTC, nlohmann requested changes

2020-11-07 13:08 UTC, nlohmann commented on setup.py
> +    author='',
```suggestion
    author='Niels Lohmann',
```

2020-11-07 13:08 UTC, nlohmann commented on setup.py
> +    author_email='',
```suggestion
    author_email='mail@nlohmann.me',
```

2020-11-07 13:08 UTC, nlohmann commented on setup.py
> +    url='',
```suggestion
    url='http://nlohmann.me',
```

2020-11-07 13:08 UTC, nlohmann commented on setup.py
> +    keywords='swagger uml',
```suggestion
    keywords='swagger uml plantuml',
```

2020-11-07 13:08 UTC, nlohmann commented on setup.py
> +)
Pllease also add

```py
license='MIT'
```

2020-11-11 10:05 UTC, rodfersou commented on setup.py
> +)
done

2020-11-11 10:06 UTC, rodfersou commented
done

2020-12-03 06:33 UTC, rodfersou commented
@nlohmann any reason for not merge this branch?

2020-12-04 09:53 UTC, nlohmann commented
There is still an open suggestion regarding the email.

2020-12-23 07:01 UTC, rodfersou commented
I see, sorry, didn't see that, done!

2020-12-23 09:55 UTC, nlohmann approved these changes
Looks good to me.

2020-12-23 09:55 UTC, merged

2020-12-23 09:55 UTC, nlohmann commented
Thanks!